In [2]:
import pandas as pd

# Load behavioral data (as per user's path)
behav = pd.read_csv("/home/jovyan/cache/memoryNSD/sub01_behav.tsv", sep='\t')

# Filter for shared1000 images only
shared = behav[behav["is_shared1000"] == 1]

# Separate encoding and retrieval trials
encoding = shared[shared["shared1000_repNum"] == 1].copy()
retrieval1 = shared[shared["shared1000_repNum"] == 2].copy()

# Match encoding and retrieval trials by image ID (10KID)
item_pairs = pd.merge(
    encoding,
    retrieval1,
    on="10KID",
    suffixes=("_enc", "_ret")
)

# Show results
item_pairs[["10KID", "TRIAL_enc", "TRIAL_ret", "ISCORRECT_enc", "ISCORRECT_ret"]].head()

   10KID  TRIAL_enc  TRIAL_ret  ISCORRECT_enc  ISCORRECT_ret
0    626          1         53            1.0            0.0
1    666         29         49            1.0            0.0
2    612         36          2            1.0            1.0
3    436         45         28            1.0            1.0
4    727         56         41            1.0            0.0